name: Update Welfare Data

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정(0시)에 자동으로 실행
  workflow_dispatch: # 내가 원할 때 수동으로 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 소스코드
        uses: actions/checkout@v3

      - name: 노드 설치
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 라이브러리 설치
        run: npm install node-fetch xml2js

      - name: 크롤러 실행
        run: node crawler.mjs

      - name: 변경사항 저장 및 푸시
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add policies.json
          git commit -m "Auto update: policies.json" || exit 0
          git push
